version: '2'
services:

  bitcoind:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .bitcoin:/data/.bitcoin
    ports:
      - 8332:8332
    labels:
      lagoon.type: basic-persistent
      lagoon.persistent: /data/.bitcoin
      lagoon.service.port: 8332
    environment:
      LAGOON_LOCALDEV_HTTP_PORT: 8332
      LAGOON_ROUTE: http://bitcoind-grpc.docker.amazee.io


networks:
  amazeeio-network:
    external: true
